#!/bin/bash
podman build --userns-uid-map=0:0:1 --userns-uid-map=1:1:1999 --userns-uid-map=65534:2000:2 ./podman_dir -t hxn-ptycho-holoscan --network host

echo "### If build container failed because of permission issues, remove all contents of /var/tmp/<your username>/ folder and build again. ###"
ROOT_HOME_DIR="$HOME/.ptycho_gui/root_home"
SOURCE_FILE="./podman_dir/bashrc_template"
mkdir -p "$ROOT_HOME_DIR"
if [ ! -f "$ROOT_HOME_DIR/.bashrc" ]; then
    cp "$SOURCE_FILE" "$ROOT_HOME_DIR/.bashrc"
    echo "#################################### CAUTION ####################################"
    echo "Copied fresh bashrc template file to $ROOT_HOME_DIR/.bashrc, the socket keys need to be set there."
    echo "Refer to proxy config files on IOC servers or sample scripts."
    echo "#################################################################################"
else
    echo "# $ROOT_HOME_DIR/.bashrc already exists, keeping the current file. #"
fi
