#!/bin/bash
if [ $# == 0 ]; then
	ARG="shell"
else
	ARG="$*"
fi
podman run --rm --net host -it \
--shm-size=32g \
-v ./podman_dir:/podman_dir \
-v ../:/ptycho_gui_holoscan \
-v "$HOME/.Xauthority:/root/.Xauthority:rw" \
-v /nsls2/data/hxn/legacy:/nsls2/data2/hxn/legacy \
-v /nsls2/data/hxn/legacy:/nsls2/data/hxn/legacy \
-v /nsls2/data/hxn/legacy:/data \
-v /nsls2/data/hxn/legacy/home/xf03id/src/hxntools:/hxntools \
-v $HOME/.ptycho_gui/root_home:/root \
-w /podman_dir \
-e DISPLAY="$DISPLAY" \
-e OMPI_ALLOW_RUN_AS_ROOT=1 \
-e OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
-e OMPI_COMM_WORLD_LOCAL_RANK=0 \
-e OMPI_COMM_WORLD_LOCAL_SIZE=1 \
-e HOLOSCAN_ENABLE_PROFILE=1 \
--device nvidia.com/gpu=all \
hxn-ptycho-holoscan pixi $ARG
